---
all:
  children:
    prod_servers:
      children:
        db1:
          hosts:
            server1: 
              ansible_host: 192.168.10.10
        db2:
          hosts:
            server2: 
              ansible_host: 192.168.10.11